apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: dxpsharedpvc
  namespace: dxp
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
