apiVersion: v1
kind: Service
metadata:
  name: dxpserver-service
  namespace: dxp
spec:
  ports:
  - name: dxpserver
    protocol: TCP
    port: 8094
    targetPort: 8080
  selector:
    app: dxpserver

