apiVersion: v1
kind: PersistentVolume
metadata: 
  labels: 
    app: postgres
    type: local
  name: postgres-pv-volume
  
spec: 
  accessModes: 
    - ReadWriteMany
  capacity: 
    storage: 2Gi
  hostPath: 
    path: "/mnt/data"
  storageClassName: manual

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata: 
  labels: 
    app: postgres
  name: postgres-pv-claim
  namespace: dxp
spec: 
  accessModes: 
    - ReadWriteMany
  resources: 
    requests: 
      storage: 2Gi
  storageClassName: manual
