apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-config
  namespace: dxp
  labels:
    app: postgres
data:
  POSTGRES_DB: ibpmdb
  POSTGRES_USER: postgres
  POSTGRES_PASSWORD: Fujitsu1
  PGDATA: /var/lib/postgresql/data/pgdata
