apiVersion: v1
kind: Service
metadata:
  name: postgres-service
  namespace: dxp
  labels:
    app: db-server
spec:
  selector:
   app: db-server
  ports:
   - protocol: TCP
     port: 5432
     targetPort: 5432


